### ISSUE TITLE
如何导入进IDE

### ISSUE THREAD

**Issue by crossoverJie** [reedmi/drp#3]
你好，我是第一次准备参与一个别人的开源项目，发现你的项目和我目前从事的差不多，但是却不知道怎么导入eclipse中。。。谢谢。

**Comment by caicf** [comment]
import ExistsMaven Project

**Comment by crossoverJie** [comment]
> import ExistsMaven Project

成功导入，谢谢。

**Comment by rpgmakervx** [comment]
建议用idea，maven支持很不错哦！

**Comment by crossoverJie** [comment]
> 建议用idea，maven支持很不错哦！

有用过，只是刚开始用着不太习惯，而且公司也没有用，所以就放弃了。。。
