### ISSUE TITLE
目录貌似出错了

### ISSUE THREAD

**Issue by crossoverJie** [reedmi/drp#4]
jdbc.properties的目录在 filters/dev/jdbc.properties目录下，但是目前代码的目录是 filters/prod/jdbc.properties 导致eclipse build项目时报错。

**Comment by ghost** [comment]
请查看wiki，运行说明步骤2，添加相关目录和文件

**Comment by crossoverJie** [comment]
> 请查看wiki，运行说明步骤2，添加相关目录和文件
> 我自己眼神问题，已解决。
